name: "EarmuffsAction"
description: "Status check source code for foul language."
author: "Danny Hinshaw"
branding:
  icon: alert-triangle
  color: yellow

inputs:
  EXCLUDE_FILES:
    description: "Regular expression of files to ignore."
    default: "\\.idea|\\.git|node_modules"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
